### ISSUE TITLE
[Feature]: 希望添加快捷键窗口(Shift)和预设几个快捷键

### ISSUE THREAD

**Issue by RicharPao** [wleelw/hexo-theme-solitude#112]
### 想要的功能 | What feature do you want?

希望可以添加快捷键和洪哥那个左上角的窗口，除了js监听键盘以外Accesskey好像也不错，直接放到标签里面，缺点就是只能用Alt触发，因为这个东西的初衷是给无障碍用的
Shift + KEY 的快捷键可以让老用户有更加流畅的体验，实现这个功能并不困难：
**以切换显示模式为例 <kbd>Shift</kbd> + <kbd>D</kbd>**
```js
document.addEventListener('keydown', function(event) {
  // 检查是否按下了Shift+D
  if (event.shiftKey && event.key === 'D') {
    // 调用切换显示模式的函数
    sco.switchDarkMode();
  }
});
```

**但是这样会导致在评论区输入大写字母时触发，可以添加一个条件来检查焦点是否在输入框内**

```js
document.addEventListener('keydown', function(event) {
  // 检查是否按下了Shift+D，并且焦点不在输入框内
  if (!event.target.matches('input, textarea') && event.shiftKey && event.key === 'D') {
    // 调用切换显示模式的函数
    sco.switchDarkMode();
  }
});
```

以此类推...
主要是我认为全部快捷键窗口这个功能有点必要，希望可以添加并在配置文件中可以修改

```yaml
key:
  enable: true|false
  position: top-left | top-right | center and more...
  keys:
    切换显示模式:
      text:
      key:
      url/javascript: 函数、跳转网址等
    返回首页:
      ...
      url: /
```

类似这种吧，主要是添加一个新的窗口，自定义快捷键用户可以自己引入js
